#

pluginName = PetriNet Model Edit Support
providerName = www.example.org

_UI_CreateChild_text = {0}
_UI_CreateChild_text2 = {1} {0}
_UI_CreateChild_text3 = {1}
_UI_CreateChild_tooltip = Create New {0} Under {1} Feature
_UI_CreateChild_description = Create a new child of type {0} for the {1} feature of the selected {2}.
_UI_CreateSibling_description = Create a new sibling of type {0} for the selected {2}, under the {1} feature of their parent.

_UI_PropertyDescriptor_description = The {0} of the {1}

_UI_Transition_type = Transition
_UI_Place_type = Place
_UI_PetriNet_type = Petri Net
_UI_Arc_type = Arc
_UI_Objet_type = Objet
_UI_Unknown_type = Object

_UI_Unknown_datatype= Value

_UI_Transition_temp_min_feature = Temp min
_UI_Transition_temp_max_feature = Temp max
_UI_Place_token_feature = Token
_UI_PetriNet_name_feature = Name
_UI_PetriNet_objet_feature = Objet
_UI_PetriNet_arc_feature = Arc
_UI_Arc_token_feature = Token
_UI_Arc_Predecessor_link_feature = Predecessor link
_UI_Arc_Successor_link_feature = Successor link
_UI_Arc_petrinet_feature = Petrinet
_UI_Objet_name_feature = Name
_UI_Objet_Successor_feature = Successor
_UI_Objet_Predecessor_feature = Predecessor
_UI_Objet_petrinet_feature = Petrinet
_UI_Unknown_feature = Unspecified

