<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Petrinet" nsURI="Petrinet" nsPrefix="Petrinet">
  <eClassifiers xsi:type="ecore:EClass" name="Transition" eSuperTypes="#//NodeDefinition"/>
  <eClassifiers xsi:type="ecore:EClass" name="Place" eSuperTypes="#//NodeDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="token" upperBound="-1"
        eType="#//Token" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Token"/>
  <eClassifiers xsi:type="ecore:EClass" name="PetriNet">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodedefinition" upperBound="-1"
        eType="#//NodeDefinition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodesequence" upperBound="-1"
        eType="#//NodeSequence" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NodeSequence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//NodeDefinition" eOpposite="#//NodeDefinition/linkstoSuccessor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="predecessor" lowerBound="1"
        eType="#//NodeDefinition" eOpposite="#//NodeDefinition/linkstoPredecessor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NodeDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="linkstoSuccessor" eType="#//NodeSequence"
        eOpposite="#//NodeSequence/source"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="linkstoPredecessor" eType="#//NodeSequence"
        eOpposite="#//NodeSequence/predecessor"/>
  </eClassifiers>
</ecore:EPackage>
