/**
 * generated by Xtext 2.32.0
 */
package fr.n7.pDL1.impl;

import fr.n7.pDL1.PDL1Package;
import fr.n7.pDL1.RessourceUsage;
import fr.n7.pDL1.Ressources;
import fr.n7.pDL1.WorkDefinition;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Ressource Usage</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.pDL1.impl.RessourceUsageImpl#getQuantity <em>Quantity</em>}</li>
 *   <li>{@link fr.n7.pDL1.impl.RessourceUsageImpl#getWorkdefinition <em>Workdefinition</em>}</li>
 *   <li>{@link fr.n7.pDL1.impl.RessourceUsageImpl#getRessource <em>Ressource</em>}</li>
 * </ul>
 *
 * @generated
 */
public class RessourceUsageImpl extends MinimalEObjectImpl.Container implements RessourceUsage
{
  /**
   * The default value of the '{@link #getQuantity() <em>Quantity</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getQuantity()
   * @generated
   * @ordered
   */
  protected static final int QUANTITY_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getQuantity() <em>Quantity</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getQuantity()
   * @generated
   * @ordered
   */
  protected int quantity = QUANTITY_EDEFAULT;

  /**
   * The cached value of the '{@link #getWorkdefinition() <em>Workdefinition</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getWorkdefinition()
   * @generated
   * @ordered
   */
  protected WorkDefinition workdefinition;

  /**
   * The cached value of the '{@link #getRessource() <em>Ressource</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRessource()
   * @generated
   * @ordered
   */
  protected Ressources ressource;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RessourceUsageImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PDL1Package.Literals.RESSOURCE_USAGE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getQuantity()
  {
    return quantity;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setQuantity(int newQuantity)
  {
    int oldQuantity = quantity;
    quantity = newQuantity;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PDL1Package.RESSOURCE_USAGE__QUANTITY, oldQuantity, quantity));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public WorkDefinition getWorkdefinition()
  {
    if (workdefinition != null && workdefinition.eIsProxy())
    {
      InternalEObject oldWorkdefinition = (InternalEObject)workdefinition;
      workdefinition = (WorkDefinition)eResolveProxy(oldWorkdefinition);
      if (workdefinition != oldWorkdefinition)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, PDL1Package.RESSOURCE_USAGE__WORKDEFINITION, oldWorkdefinition, workdefinition));
      }
    }
    return workdefinition;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public WorkDefinition basicGetWorkdefinition()
  {
    return workdefinition;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setWorkdefinition(WorkDefinition newWorkdefinition)
  {
    WorkDefinition oldWorkdefinition = workdefinition;
    workdefinition = newWorkdefinition;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PDL1Package.RESSOURCE_USAGE__WORKDEFINITION, oldWorkdefinition, workdefinition));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Ressources getRessource()
  {
    if (ressource != null && ressource.eIsProxy())
    {
      InternalEObject oldRessource = (InternalEObject)ressource;
      ressource = (Ressources)eResolveProxy(oldRessource);
      if (ressource != oldRessource)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, PDL1Package.RESSOURCE_USAGE__RESSOURCE, oldRessource, ressource));
      }
    }
    return ressource;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Ressources basicGetRessource()
  {
    return ressource;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRessource(Ressources newRessource)
  {
    Ressources oldRessource = ressource;
    ressource = newRessource;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PDL1Package.RESSOURCE_USAGE__RESSOURCE, oldRessource, ressource));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PDL1Package.RESSOURCE_USAGE__QUANTITY:
        return getQuantity();
      case PDL1Package.RESSOURCE_USAGE__WORKDEFINITION:
        if (resolve) return getWorkdefinition();
        return basicGetWorkdefinition();
      case PDL1Package.RESSOURCE_USAGE__RESSOURCE:
        if (resolve) return getRessource();
        return basicGetRessource();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PDL1Package.RESSOURCE_USAGE__QUANTITY:
        setQuantity((Integer)newValue);
        return;
      case PDL1Package.RESSOURCE_USAGE__WORKDEFINITION:
        setWorkdefinition((WorkDefinition)newValue);
        return;
      case PDL1Package.RESSOURCE_USAGE__RESSOURCE:
        setRessource((Ressources)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PDL1Package.RESSOURCE_USAGE__QUANTITY:
        setQuantity(QUANTITY_EDEFAULT);
        return;
      case PDL1Package.RESSOURCE_USAGE__WORKDEFINITION:
        setWorkdefinition((WorkDefinition)null);
        return;
      case PDL1Package.RESSOURCE_USAGE__RESSOURCE:
        setRessource((Ressources)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PDL1Package.RESSOURCE_USAGE__QUANTITY:
        return quantity != QUANTITY_EDEFAULT;
      case PDL1Package.RESSOURCE_USAGE__WORKDEFINITION:
        return workdefinition != null;
      case PDL1Package.RESSOURCE_USAGE__RESSOURCE:
        return ressource != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (quantity: ");
    result.append(quantity);
    result.append(')');
    return result.toString();
  }

} //RessourceUsageImpl
