/**
 * generated by Xtext 2.32.0
 */
package fr.n7.pDL1;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ressource Usage</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.pDL1.RessourceUsage#getQuantity <em>Quantity</em>}</li>
 *   <li>{@link fr.n7.pDL1.RessourceUsage#getWorkdefinition <em>Workdefinition</em>}</li>
 *   <li>{@link fr.n7.pDL1.RessourceUsage#getRessource <em>Ressource</em>}</li>
 * </ul>
 *
 * @see fr.n7.pDL1.PDL1Package#getRessourceUsage()
 * @model
 * @generated
 */
public interface RessourceUsage extends EObject
{
  /**
   * Returns the value of the '<em><b>Quantity</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Quantity</em>' attribute.
   * @see #setQuantity(int)
   * @see fr.n7.pDL1.PDL1Package#getRessourceUsage_Quantity()
   * @model
   * @generated
   */
  int getQuantity();

  /**
   * Sets the value of the '{@link fr.n7.pDL1.RessourceUsage#getQuantity <em>Quantity</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Quantity</em>' attribute.
   * @see #getQuantity()
   * @generated
   */
  void setQuantity(int value);

  /**
   * Returns the value of the '<em><b>Workdefinition</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Workdefinition</em>' reference.
   * @see #setWorkdefinition(WorkDefinition)
   * @see fr.n7.pDL1.PDL1Package#getRessourceUsage_Workdefinition()
   * @model
   * @generated
   */
  WorkDefinition getWorkdefinition();

  /**
   * Sets the value of the '{@link fr.n7.pDL1.RessourceUsage#getWorkdefinition <em>Workdefinition</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Workdefinition</em>' reference.
   * @see #getWorkdefinition()
   * @generated
   */
  void setWorkdefinition(WorkDefinition value);

  /**
   * Returns the value of the '<em><b>Ressource</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ressource</em>' reference.
   * @see #setRessource(Ressources)
   * @see fr.n7.pDL1.PDL1Package#getRessourceUsage_Ressource()
   * @model
   * @generated
   */
  Ressources getRessource();

  /**
   * Sets the value of the '{@link fr.n7.pDL1.RessourceUsage#getRessource <em>Ressource</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ressource</em>' reference.
   * @see #getRessource()
   * @generated
   */
  void setRessource(Ressources value);

} // RessourceUsage
