grammar fr.n7.PDL1 with org.eclipse.xtext.common.Terminals
generate pDL1 "http://www.n7.fr/PDL1"

Process :
	'process' name=ID '{'
	    processElements+=ProcessElement*
	'}' ;

ProcessElement :
	WorkDefinition | WorkSequence | Guidance | Ressources;
	
Ressources : 
	'r' name=ID 
		'quantity' amount=INT ;
	
ResourceUsage :
	'ru' quantity=INT
		'by' workdefinition=[WorkDefinition]
		'from' ressource=[Ressources] ;

WorkDefinition :
	'wd' name=ID
	    ( 'uses' resourceusage+=ResourceUsage+ )?;

WorkSequence :
	'ws' linkType=WorkSequenceType
		'from' predecessor=[WorkDefinition]
		'to' successor=[WorkDefinition] ;

Guidance :
	'note' texte=STRING ;

enum WorkSequenceType :
	start2start='s2s'
	| finish2start='f2s'
	| start2finish='s2f'
	| finish2finish='f2f'
	;
